# config/database.yml
development:
  adapter: sqlite3
  database: barbershop.db

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: sqlite3
  database: db/production.sqlite3
